#!/usr/bin/env python3
"""
Generate a daily podcast briefing from feed-podcasts.json and send via Resend.
Env vars: RESEND_API_KEY, RECIPIENT_EMAIL
"""

import json
import os
import subprocess
import sys
from datetime import datetime, timedelta, timezone
from urllib.request import Request, urlopen
from urllib.error import HTTPError

FEED_URL = "https://raw.githubusercontent.com/jjd200099-crypto/follow-builders/main/feed-podcasts.json"
RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")
RECIPIENT = os.environ.get("RECIPIENT_EMAIL", "")


def fetch_feed():
    req = Request(FEED_URL)
    with urlopen(req) as resp:
        return json.loads(resp.read().decode("utf-8"))


def send_email(subject, text_body):
    data = json.dumps({
        "from": "Follow Builders <onboarding@resend.dev>",
        "to": RECIPIENT,
        "subject": subject,
        "text": text_body,
    }).encode()

    req = Request(
        "https://api.resend.com/emails",
        data=data,
        headers={
            "Authorization": f"Bearer {RESEND_API_KEY}",
            "Content-Type": "application/json",
        },
    )
    try:
        with urlopen(req) as resp:
            result = json.loads(resp.read())
            print(f"Email sent! ID: {result.get('id')}", file=sys.stderr)
    except HTTPError as e:
        print(f"Email error {e.code}: {e.read().decode()}", file=sys.stderr)
        sys.exit(1)


def main():
    if not RESEND_API_KEY or not RECIPIENT:
        print("RESEND_API_KEY or RECIPIENT_EMAIL not set", file=sys.stderr)
        sys.exit(0)

    print("Fetching feed...", file=sys.stderr)
    feed = fetch_feed()
    podcasts = feed.get("podcasts", [])

    # Filter last 24 hours
    cutoff = datetime.now(timezone.utc) - timedelta(hours=24)
    recent = []
    for ep in podcasts:
        pub = ep.get("publishedAt", "")
        if not pub:
            continue
        try:
            dt = datetime.fromisoformat(pub.replace("Z", "+00:00"))
            if dt >= cutoff:
                recent.append(ep)
        except ValueError:
            pass

    if not recent:
        print("No new episodes in the past 24 hours", file=sys.stderr)
        sys.exit(0)

    # Sort newest first
    recent.sort(key=lambda x: x.get("publishedAt", ""), reverse=True)

    today = datetime.now(timezone(timedelta(hours=8))).strftime("%Y-%m-%d")
    separator = "─" * 40

    lines = [
        "=" * 64,
        f"  🎙 Podcast Daily Briefing — {today}",
        f"  过去 24 小时共 {len(recent)} 期新节目",
        "=" * 64,
        "",
    ]

    for i, ep in enumerate(recent, 1):
        name = ep.get("name", "Unknown")
        title = ep.get("title", "Untitled")
        url = ep.get("url", "")
        pub = ep.get("publishedAt", "")[:16].replace("T", " ")

        lines.append(f"{i}. [{name}] {title}")
        lines.append(f"   {pub}")
        if url:
            lines.append(f"   {url}")
        lines.append("")
        lines.append(separator)
        lines.append("")

    lines.append("=" * 64)
    lines.append("  Generated by Follow Builders")
    lines.append("=" * 64)

    subject = f"🎙 Podcast Daily Briefing — {today} ({len(recent)} new episodes)"
    body = "\n".join(lines)

    print(f"Sending: {subject}", file=sys.stderr)
    send_email(subject, body)


if __name__ == "__main__":
    main()
